- name: Set the default projects template with Limits and NetworkPolicy defaults
  hosts: masters[0]
  become_user: root
  become: yes
  tasks:
    - name: Execute the script
      script: ../scripts/set_default_project.sh
