- name: Set the default projects template with Limits and NetworxPolicy defaults
  hosts: masters[0]
  remote_user: root
  sudo: yes
  tasks:
    - name: Execute the script
      script: ../scripts/set_default_project.sh
